--Within Distance

SELECT
   aid.NAVIGATIONAL_AID_ID, ipr.INTRID_SID, ipr.TRANSACTION_SID,
   ROUND(SDO_GEOM.SDO_DISTANCE(ipr.SHAPE, aid.GEOMETRY, 0.005),2) DISTANCE
 
FROM
  WHSE_TANTALIS.TA_INTEREST_PARCEL_SHAPES ipr,
  WHSE_ENVIRONMENTAL_MONITORING.CHRA_NAVIGATIONAL_AIDS_POINT aid

   WHERE aid.NAVIGATIONAL_AID_ID IN (700,701,704,708,684,678,675)
     AND  SDO_WITHIN_DISTANCE (ipr.SHAPE, aid.GEOMETRY, 'distance=200 unit=m') = 'TRUE';
     
     
    
    
--Relate
SELECT
   ipr.INTRID_SID, pip.CNSLTN_AREA_NAME, pip.CONTACT_ORGANIZATION_NAME,
   ROUND((SDO_GEOM.SDO_AREA(SDO_GEOM.SDO_INTERSECTION(pip.SHAPE,ipr.SHAPE, 0.005), 0.005, 'unit=HECTARE')/ 
   SDO_GEOM.SDO_AREA(ipr.SHAPE, 0.005, 'unit=HECTARE'))*100, 2) OVERLAP_PERCENT

FROM
    WHSE_TANTALIS.TA_INTEREST_PARCEL_SHAPES ipr
      INNER JOIN WHSE_ADMIN_BOUNDARIES.PIP_CONSULTATION_AREAS_SP pip 
        ON SDO_RELATE (pip.SHAPE, ipr.SHAPE, 'mask=ANYINTERACT') = 'TRUE'

 WHERE pip.CNSLTN_AREA_NAME = q'[Hul'qumi'num Nations - Marine Territory]'
   AND ipr.INTRID_SID IN (XXXXXX);
   


-- Relate 2 (Nested Queries)
SELECT*

FROM
WHSE_TANTALIS.TA_CROWN_TENURES_SVW ipr
INNER JOIN WHSE_ADMIN_BOUNDARIES.PIP_CONSULTATION_AREAS_SP pip 
ON SDO_RELATE (pip.SHAPE, ipr.SHAPE, 'mask=ANYINTERACT') = 'TRUE'

WHERE ipr.INTRID_SID IN ( SELECT ipr2.INTRID_SID
                           FROM
                           WHSE_TANTALIS.TA_CROWN_TENURES_SVW ipr2
                             INNER JOIN WHSE_ADMIN_BOUNDARIES.PIP_CONSULTATION_AREAS_SP pip 
                           ON SDO_RELATE (pip.SHAPE, ipr.SHAPE, 'mask=ANYINTERACT') = 'TRUE'
                           
                            WHERE pip.CNSLTN_AREA_NAME = q'[Shishalh (Sechelt) First Nation]'
                            AND ipr2.INTRID_SID IN (XXXX)
                            );



-- Nearest Neighbor
SELECT ten.INTRID_SID, pp.PID, pp.OWNER_TYPE,  ROUND(SDO_NN_DISTANCE(1),1) PROXIMITY_METERS 

FROM WHSE_CADASTRE.PMBC_PARCEL_FABRIC_POLY_SVW pp,
    WHSE_TANTALIS.TA_INTEREST_PARCEL_SHAPES ten

WHERE ten.INTRID_SID = XXXX
  AND pp.OWNER_TYPE = 'Private'
  AND SDO_NN(pp.SHAPE, ten.SHAPE, 'sdo_num_res={n_neighbor}' ,1) = 'TRUE'
   
   
   
